version: '3.8'

services:

  bf-frontend:
    build:
      context: ./frontend       # Now using the frontend folder
      dockerfile: Dockerfile      # Use your Vue app's Dockerfile here (see note below)
    ports:
      - "8078:80"               # Exposing frontend on port 8081 (or adjust as needed)
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hdb-frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
      
networks:
  traefik-net:
    external: true
