version: '3.8'

services:
  rc-frontend:
    image: docker.goodgermy.com/nexus/recollective-frontend:latest
    container_name: rc-frontend
    env_file:
      - .env.production.frontend
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.services.rc-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.rc-frontend.rule=Host(`recollectivect.com`,`www.recollectivect.com`)"
      - "traefik.http.routers.rc-frontend.entrypoints=websecure"
      - "traefik.http.routers.rc-frontend.tls=true"
      - "traefik.http.routers.rc-frontend.tls.certresolver=default-resolver"

  rc-backend:
    image: docker.goodgermy.com/nexus/oauth:latest
    container_name: rc-backend
    env_file:
      - .env.production.backend
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/nexus/recollective/rc-backend/tokens:/app/tokens"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.rc-backend.rule=Host(`api.recollectivect.com`)"
      - "traefik.http.routers.rc-backend.entrypoints=websecure"
      - "traefik.http.routers.rc-backend.tls=true"
      - "traefik.http.routers.rc-backend.tls.certresolver=default-resolver"
      - "traefik.http.services.rc-backend.loadbalancer.server.port=8000"

  rc-minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: rc-minio
    env_file:
      - .env.production.minio
    environment:
      MINIO_BROWSER_REDIRECT_URL: "https://console.media.recollectivect.com"
      MINIO_NOTIFY_WEBHOOK_ENABLE_RESIZER: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_RESIZER: "http://rc-image-resizer:8080/events"
      MINIO_NOTIFY_WEBHOOK_QUEUE_DIR_RESIZER: "/data/.minio.sys/queue"
      MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT_RESIZER: "0"
    restart: unless-stopped
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/nexus/recollective/rc-minio-data:/data"
      - ./deploy-scripts/init-minio.sh:/init-minio.sh
    entrypoint: ["/bin/sh", "-c", "chmod +x /init-minio.sh && /init-minio.sh && minio server /data --console-address ':9001'"]
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rc-minio-api.rule=Host(`media.recollectivect.com`)"
      - "traefik.http.routers.rc-minio-api.entrypoints=websecure"
      - "traefik.http.routers.rc-minio-api.tls=true"
      - "traefik.http.routers.rc-minio-api.tls.certresolver=default-resolver"
      - "traefik.http.routers.rc-minio-api.service=rc-minio-api"
      - "traefik.http.services.rc-minio-api.loadbalancer.server.port=9000"
      - "traefik.http.routers.rc-minio-console.rule=Host(`console.media.recollectivect.com`)"
      - "traefik.http.routers.rc-minio-console.entrypoints=websecure"
      - "traefik.http.routers.rc-minio-console.tls=true"
      - "traefik.http.routers.rc-minio-console.tls.certresolver=default-resolver"
      - "traefik.http.routers.rc-minio-console.service=rc-minio-console"
      - "traefik.http.services.rc-minio-console.loadbalancer.server.port=9001"

  rc-image-resizer:
    image: docker.goodgermy.com/nexus/recollective-image-resizer:latest
    container_name: rc-image-resizer
    env_file:
      - .env.production.image-resizer
    environment:
      PYTHONUNBUFFERED: "1"
    command:
      - python
      - -u
      - app.py
    depends_on:
      - rc-minio
    restart: unless-stopped
    networks:
      - traefik-net
    expose:
      - "8080"

  rc-strapi:
    image: docker.goodgermy.com/strapi:dev-latest
    container_name: rc-strapi
    env_file:
      - .env.production.strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: rc-strapi-db
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: Xj9kLm2pQr4tWy8zAb3cDe5fGh7iJk9l
      DATABASE_PORT: 5432
      JWT_SECRET: 3f9k2m7p8q5r4t6w9x0y1z2a3b4c5d6e7f8g9h0i
      ADMIN_JWT_SECRET: j4k5l6m7n8p9q0r1s2t3u4v5w6x7y8z9a0b1c2d
      API_TOKEN_SALT: t2u3v4w5x8y7z8a9b0c1d2e3f4g5h6i7j8k9l0m
      APP_KEYS: k9m0n1p2q3r4s5t6u7v8w9x0y1z2a3b4,c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1337
      APP_URL: https://cms.recollectivect.com
      STRAPI_ADMIN_EMAIL: info@recollectivect.com
      STRAPI_ADMIN_PASSWORD: nextstep
      STRAPI_ADMIN_FIRSTNAME: NextStep
      STRAPI_ADMIN_LASTNAME: Admin
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/nexus/recollective/rc-strapi/public/uploads:/opt/app/public/uploads"
    restart: unless-stopped
    networks:
      - traefik-net
    depends_on:
      - rc-strapi-db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.rc-strapi.rule=Host(`cms.recollectivect.com`)"
      - "traefik.http.routers.rc-strapi.entrypoints=websecure"
      - "traefik.http.routers.rc-strapi.tls=true"
      - "traefik.http.routers.rc-strapi.tls.certresolver=default-resolver"
      - "traefik.http.services.rc-strapi.loadbalancer.server.port=1337"

  rc-strapi-db:
    image: postgres:14.5-alpine
    container_name: rc-strapi-db
    env_file:
      - .env.production.strapi
    volumes:
      - "${MY_DOCKER_DATA_PATH:-~/mydata}/nexus/recollective/rc-strapi-db:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - traefik-net
    expose:
      - "5432"

  rc-strapi-adminer:
    image: adminer:latest
    container_name: rc-strapi-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: rc-strapi-db
    networks:
      - traefik-net
    depends_on:
      - rc-strapi-db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.rc-strapi-adminer.rule=Host(`adminer.recollectivect.com`)"
      - "traefik.http.routers.rc-strapi-adminer.entrypoints=websecure"
      - "traefik.http.routers.rc-strapi-adminer.tls=true"
      - "traefik.http.routers.rc-strapi-adminer.tls.certresolver=default-resolver"
      - "traefik.http.services.rc-strapi-adminer.loadbalancer.server.port=8080"

networks:
  traefik-net:
    external: true