name: Build and Publish Docker Images

# Trigger on push to production branch only
on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    name: Build & Push All Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Private Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.goodgermy.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.goodgermy.com/nexus/recollective-frontend:latest

      - name: Build and push image-resizer image
        uses: docker/build-push-action@v4
        with:
          context: ./image-resizer
          file: ./image-resizer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.goodgermy.com/nexus/recollective-image-resizer:latest
